=== UzielGarcia1/40260/xml/gramatica.dtd
<!ELEMENT restaurante (platillo+, bebida+)>

<!ELEMENT platillo (nombre, precio)>
<!ATTLIST platillo id CDATA #REQUIRED>

<!ELEMENT bebida (nombre, precio)>
<!ATTLIST bebida id CDATA #REQUIRED>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT precio (#PCDATA)>

=== UzielGarcia1/40260/xml/gramatica.xml
<?xml version="1.0"?>
<!DOCTYPE restaurante SYSTEM "gramatica.dtd">

<restaurante>
  <platillo id="P01">
    <nombre>Tacos</nombre>
    <precio>50</precio>
  </platillo>

  <platillo id="P02">
    <nombre>Quesadilla</nombre>
    <precio>35</precio>
  </platillo>

  <bebida id="B01">
    <nombre>Agua de horchata</nombre>
    <precio>20</precio>
  </bebida>
</restaurante>
